[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.2"
regex = "1.11.1"

[profile.speed_opt]
inherits = "release"
debug = 0
codegen-units = 1
opt-level = 3
strip = "debuginfo"
